name: Generate GitHub Stats

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: yasmim-passos
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
      - name: Commit metrics
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add metrics.svg || true
          git commit -m "Update metrics" || echo "No changes"
          git push
